const ActionTypes = {
    // Common
    BEGIN_LOADING: 'BEGIN_LOADING',
    END_LOADING: 'END_LOADING',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    REDIRECT: 'REDIRECT',
    CLEAR_PATH: 'CLEAR_PATH',
    SET_VALIDSTATUS: 'SET_VALIDSTATUS',
    EMPTY: 'EMPTY',
    CANCEL: 'CANCEL',
    // Auth
    SIGNIN: 'SIGNIN',
    SIGNOUT: 'SIGNOUT',
    // Setting
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    INIT_LANDINGPAGE: 'INIT_LANDINGPAGE',
    LOAD_LANDING: 'LOAD_LANDING',
    // Biz
    INIT_SHIPPINGLANEPAGE: 'INIT_SHIPPINGLANEPAGE',
    LOAD_SHIPPINGLANE: 'LOAD_SHIPPINGLANE',
    START_SHIPPINGLANE: 'START_SHIPPINGLANE',
    CLOSE_SHIPPINGLANE: 'CLOSE_SHIPPINGLANE',
    ADD_SHIPPINGLANE: 'ADD_SHIPPINGLANE',
    REMOVE_SHIPPINGLANE: 'REMOVE_SHIPPINGLANE',
    ENABLE_ISTIO: 'ENABLE_ISTIO',
    DISABLE_ISTIO: 'DISABLE_ISTIO',
    ENABLE_ISTIOSTATUS: 'ENABLE_ISTIOSTATUS',
    DISABLE_ISTIOSTATUS: 'DISABLE_ISTIOSTATUS',
    INIT_CONTAINERSHIPPAGE: 'INIT_CONTAINERSHIPPAGE',
    LOAD_CONTAINERSHIP: 'LOAD_CONTAINERSHIP',
}
export default ActionTypes;