export default {

    'Navigation.Landing': 'Landing',
    'Navigation.Terminal': 'Terminal',
    'Navigation.ContainerShip': 'Container Ship',
    'Navigation.Shipyard': 'Shipyard',
    'Navigation.Captain': 'Captain',
    'Navigation.Credential': 'Credential',
    'Navigation.QuayArea': 'Quay Area',
    'Navigation.About': 'About',
    'Navigation.Country': 'Country',
    'Navigation.ShippingLine': 'Shipping Line',
    'Navigation.GateArea': 'Gate Area',
    'Message.UsernameOrPasswordIsNotValid': 'The username or password is not valid!',
    'Message.NetworkException': 'Network Exception: {errorMessage}',
    'Message.BusinessException': 'Business Exception: {errorMessage}',
    'Message.GateRequired': 'Please input gate!',
    'Message.404': '404',
    'Message.404Caption': 'Sinking Ship! The page you visited does not exist.',
    'Message.Crush': 'Crush',
    'Message.CrushCaption': 'The terminal can not connect the pod!',
    'Confirm.Delete': 'Are you sure to delete "{name}"? It cannot be recovered!',
    'Label.Brand': 'FewBox',
    'Label.OK': 'OK',
    'Label.Cancel': 'Cancel',
    'Label.Loading': 'Loading...',
    'Label.Back': 'Back',
    'Label.All': 'All',
    'Label.Copyright': 'Design & Deliver App Service by ❤ - ©FewBox 2019',
    'Label.SignIn': 'SignIn',
    'Label.SignOut': 'Sign Out',
    'Label.RememberMe': 'Remember Me',
    'Label.Name': 'Name',
    'Label.ShippingLine': 'Shipping Line',
    'Label.Berth': 'Berth',
    'Label.Crane': 'Crane',
    'Label.CellGuide': 'CellGuide',
    'Label.Numbering': 'Numbering',
    'Label.Cargo': 'Cargo',
    'Label.Spec': 'Spec',
    'Label.Gate': 'Gate',
    'Label.Bash': 'bash',
    'Label.Sh': 'sh',
    'Label.Status': 'Status',
    'Label.Age': 'Age',
    'Label.Search': 'Search',
    'Label.Horsepower': 'Horsepower',
    'Label.Displacement': 'Displacement',
    'Label.Cube': 'Cube',
    'Label.Tonnage': 'Tonnage',
    'Label.ContainerShipPositionZone': 'ContainerShip Position Zone',
    'Label.Position': 'Position',
    'Label.Alias': 'Alias',
    'Label.Government': 'Government',
    'Label.Constitution': 'Constitution',
    'Label.Industry': 'Industry',
    'Label.Transportation': 'Transportation',
    'Label.Cargos': 'Cargos',
    'Label.Telescope': 'Telescope',
    'Label.Compass': 'Compass',
    'Label.ContainerShipSpec': 'Ship Spec',
    'Label.Type': 'Type',
    'Label.MooringBitt': 'Bitt',
    'Label.BerthItem': 'Berth {index}',
    'Label.CargoItem': 'Cargo {index}',
    'Label.Quantity': 'Quantity',
    'Label.Country': 'Country',
    'Label.CountryPosition': 'Country Position',
    'Label.CredentialItem': 'Credential {index}',
    'Label.StampItem': 'Stamp {key}'
}