export default {
    'Navigation.Landing': 'Landing',
    'Navigation.Terminal': 'Terminal',
    'Navigation.ContainerShip': 'Container Ship',
    'Navigation.Shipyard': 'Shipyard',
    'Navigation.Captain': 'Captain',
    'Navigation.Credential': 'Credential',
    'Navigation.QuayArea': 'Quay Area',
    'Navigation.YardArea': 'Yard Area',
    'Navigation.About': 'About',
    'Navigation.Country': 'Country',
    'Navigation.ShippingLine': 'Shipping Line',
    'Navigation.GateArea': 'Gate Area',
    'Message.UsernameOrPasswordIsNotValid': 'The username or password is not valid!',
    'Message.NetworkException': 'Network Exception: {errorMessage}',
    'Message.BusinessException': 'Business Exception: {errorMessage}',
    'Message.GateRequired': 'Please input gate!',
    'Message.404': '404',
    'Message.404Caption': 'Sinking Ship! The page you visited does not exist.',
    'Message.Crush': 'Crush',
    'Message.CrushCaption': 'The terminal can not connect the pod!',
    'Confirm.Delete': 'Are you sure to delete "{name}"? It cannot be recovered!',
    'Label.Brand': 'FewBox',
    'Label.OK': 'OK',
    'Label.None': 'None',
    'Label.Rent': 'Rent (None)',
    'Label.Own': 'Own (ClientIP)',
    'Label.Address': 'Address (Exact)',
    'Label.Area': 'Area (Prefix)',
    'Label.Cancel': 'Cancel',
    'Label.Loading': 'Loading...',
    'Label.Back': 'Back',
    'Label.All': 'All',
    'Label.Copyright': 'Design & Deliver App Service by ❤ - ©FewBox 2019',
    'Label.SignIn': 'SignIn',
    'Label.SignOut': 'Sign Out',
    'Label.RememberMe': 'Remember Me',
    'Label.Name': 'Name',
    'Label.ShippingLine': 'Shipping Line',
    'Label.Shipyard': 'Shipyard',
    'Label.Berth': 'Berth',
    'Label.Crane': 'Crane',
    'Label.CellGuide': 'CellGuide',
    'Label.Numbering': 'Numbering',
    'Label.Cargo': 'Cargo',
    'Label.Spec': 'Spec',
    'Label.Gate': 'Gate',
    'Label.Bash': 'bash',
    'Label.Sh': 'sh',
    'Label.Status': 'Status',
    'Label.Age': 'Age',
    'Label.Search': 'Search',
    'Label.Horsepower': 'Horsepower',
    'Label.Displacement': 'Displacement',
    'Label.Cube': 'Cube',
    'Label.Tonnage': 'Tonnage',
    'Label.ContainerShipPositionZone': 'ContainerShip Position Zone',
    'Label.Position': 'Position',
    'Label.Alias': 'Alias',
    'Label.Government': 'Government',
    'Label.Constitution': 'Constitution',
    'Label.Industry': 'Industry',
    'Label.Transportation': 'Transportation',
    'Label.Cargos': 'Cargos',
    'Label.ContainerShipSpec': 'Ship Spec',
    'Label.Type': 'Type',
    'Label.Basic': 'Basic',
    'Label.More': 'More...',
    'Label.ContainerShipAgreementType': 'Agreement',
    'Label.BerthItem': 'Berth[{key}]',
    'Label.CargoItem': 'Cargo[{key}]',
    'Label.Quantity': 'Quantity',
    'Label.Country': 'Country',
    'Label.CountryPosition': 'Country Position',
    'Label.GateArea': 'Gate Area',
    'Label.Guideboard': 'Guideboard',
    'Label.Information': 'Information',
    'Label.CredentialItem': 'Credential[{key}]',
    'Label.DocumentItem': 'Document[{key}]',
    'Label.StampItem': 'Stamp[{key}]',
    'Label.AliasItem': 'Alias[{key}]',
    'Label.GateAreaItem': 'GateArea[{key}]',
    'Label.GuideboardItem': 'Guideboard[{key}]',
    'Label.Captain': 'Captain',
    'Label.AddCredential': 'Add Credential',
    'Label.AddDoor': 'Add Door',
    'Label.DocumentDefinition': 'Definition[{key}]',
    'Label.AddQuayArea': 'Add QuayArea'
}