import * as React from 'react';
import { Icon } from 'antd';
import ShippingLineSvg from '../../../assets/images/shippingline.svg';
import QuayAreaSvg from '../../../assets/images/quayarea.svg';
import ShipyardSvg from '../../../assets/images/shipyard.svg';
import ContainerShipSvg from '../../../assets/images/containership.svg';
import GateAreaSvg from '../../../assets/images/gatearea.svg';
import CargoPackagePolicySvg from '../../../assets/images/container.svg';
import LandingSvg from '../../../assets/images/landing.svg';
import BerthSvg from '../../../assets/images/berth.svg';
import CraneSvg from '../../../assets/images/crane.svg';
import CellGuideSvg from '../../../assets/images/cellguide.svg';
import ContainerSvg from '../../../assets/images/container.svg';
import DoorSvg from '../../../assets/images/door.svg';
import NumberingSvg from '../../../assets/images/numbering.svg';
import GateSvg from '../../../assets/images/brand.svg';
import SpecificationSvg from '../../../assets/images/brand.svg';
import WarehouseSvg from '../../../assets/images/warehouse.svg';
import CountrySvg from '../../../assets/images/country.svg';
import ReefSvg from '../../../assets/images/reef.svg';
import CrashSvg from '../../../assets/images/crash.svg';
import IstioSvg from '../../../assets/images/istio.svg';
import BrandSvg from '../../../assets/images/brand.svg';
import CargoSvg from '../../../assets/images/cargo.svg';
import SleepSvg from '../../../assets/images/sleep.svg';
import CaptainSvg from '../../../assets/images/captain.svg';
import CredentialSvg from '../../../assets/images/credential.svg';

const fontSize = { fontSize: '20px' };
export const ShippingLineIcon = props => <Icon style={fontSize} component={ShippingLineSvg} {...props} />;
export const QuayAreaIcon = props => <Icon style={fontSize} component={QuayAreaSvg} {...props} />;
export const ShipyardIcon = props => <Icon style={fontSize} component={ShipyardSvg} {...props} />;
export const ContainerShipIcon = props => <Icon style={fontSize} component={ContainerShipSvg} {...props} />;
export const GateAreaIcon = props => <Icon style={fontSize} component={GateAreaSvg} {...props} />;
export const CargoPackagePolicyIcon = props => <Icon style={fontSize} component={CargoPackagePolicySvg} {...props} />;
export const LandingIcon = props => <Icon style={fontSize} component={LandingSvg} {...props} />;
export const BerthIcon = props => <Icon style={fontSize} component={BerthSvg} {...props} />;
export const CraneIcon = props => <Icon style={fontSize} component={CraneSvg} {...props} />;
export const CellGuideIcon = props => <Icon style={fontSize} component={CellGuideSvg} {...props} />;
export const ContainerIcon = props => <Icon style={fontSize} component={ContainerSvg} {...props} />;
export const DoorIcon = props => <Icon style={fontSize} component={DoorSvg} {...props} />;
export const NumberingIcon = props => <Icon style={fontSize} component={NumberingSvg} {...props} />;
export const GateIcon = props => <Icon style={fontSize} component={GateSvg} {...props} />;
export const SpecificationIcon = props => <Icon style={fontSize} component={SpecificationSvg} {...props} />;
export const WarehouseIcon = props => <Icon style={fontSize} component={WarehouseSvg} {...props} />;
export const CountryIcon = props => <Icon style={fontSize} component={CountrySvg} {...props} />;
export const IstioIcon = props => <Icon style={fontSize} component={IstioSvg} {...props} />;
export const BrandIcon = props => <Icon style={fontSize} component={BrandSvg} {...props} />;
export const CargoIcon = props => <Icon style={fontSize} component={CargoSvg} {...props} />;
export const SleepIcon = props => <Icon style={fontSize} component={SleepSvg} {...props} />;
export const CaptainIcon = props => <Icon style={fontSize} component={CaptainSvg} {...props} />;
export const CredentialIcon = props => <Icon style={fontSize} component={CredentialSvg} {...props} />;
export const FreeTradeAreaIcon = props => <Icon style={fontSize} component={BrandIcon} {...props} />
// None style
export const ReefIcon = props => <Icon component={ReefSvg} {...props} />;
export const CrashIcon = props => <Icon component={CrashSvg} {...props} />;